from pydantic import BaseModel, Field
from typing import Dict, List, Optional
from datetime import datetime

class MarketState(BaseModel):
    """
    Canonical representation of a single market observation for one symbol.
    """
    symbol: str
    timestamp: float
    bid: float
    ask: float
    mid_price: float
    last_price: float
    spread: float
    order_book_imbalance: float
    volume: float
    vwap: float
    volatility: float
    funding_rate: float
    features: List[float] = Field(description="Strictly normalized feature vector (dim=25)")
    data_quality: float = 1.0
    
class PositionState(BaseModel):
    """
    Canonical representation of a single symbol's position.
    """
    symbol: str
    side: str = "FLAT" # FLAT, LONG, SHORT
    quantity: float = 0.0
    entry_price: float = 0.0
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    leverage: int = 10
    margin: float = 0.0
    liquidation_price: float = 0.0
    
class PortfolioState(BaseModel):
    """
    Canonical representation of the overall account.
    """
    wallet_balance: float
    equity: float
    used_margin: float
    free_margin: float
    total_unrealized_pnl: float
    total_exposure: float
    positions: Dict[str, PositionState] = Field(default_factory=dict)
    
class MacroState(BaseModel):
    """
    Canonical representation of external market conditions.
    """
    timestamp: float
    sentiment_score: float = 0.0
    volatility_expectation: float = 0.5
    regime: float = 0.0
    
class OrderRequest(BaseModel):
    """
    Canonical request generated by the AI / Execution engine.
    """
    symbol: str
    action_type: str # OPEN_LONG, OPEN_SHORT, CLOSE_LONG, CLOSE_SHORT, HOLD
    confidence: float
    requested_quantity: float
    target_position: float
    model_version: str
    timestamp: float
    
class RiskDecision(BaseModel):
    """
    Deterministic result from the RiskManager.
    """
    approved: bool
    reason: str
    adjusted_quantity: float
    max_allowed_quantity: float
    risk_flags: List[str] = Field(default_factory=list)
