from pydantic import BaseModel, Field, field_validator
from typing import Dict, List, Optional
from datetime import datetime
import math

def check_not_nan_inf(v, field_name: str):
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        raise ValueError(f"{field_name} cannot be NaN or Inf")
    return v

class SymbolState(BaseModel):
    """Canonical representation of a single tradable symbol config."""
    symbol: str
    base_asset: str
    quote_asset: str
    tick_size: float
    step_size: float
    min_notional: float

class MarketState(BaseModel):
    """Canonical representation of a single market observation for one symbol."""
    symbol: str
    timestamp: float = Field(gt=0)
    bid: float = Field(ge=0)
    ask: float = Field(ge=0)
    mid_price: float = Field(gt=0)
    last_price: float = Field(gt=0)
    spread: float = Field(ge=0)
    order_book_imbalance: float
    volume: float = Field(ge=0)
    vwap: float = Field(gt=0)
    volatility: float = Field(ge=0)
    funding_rate: float
    features: List[float] = Field(..., min_length=25, max_length=25)
    data_quality: float = Field(default=1.0, ge=0.0, le=1.0)

    @field_validator('*', mode='before')
    @classmethod
    def check_floats(cls, v, info):
        return check_not_nan_inf(v, info.field_name)

class PositionState(BaseModel):
    """Canonical representation of a single symbol's position."""
    symbol: str
    side: str = "FLAT" # FLAT, LONG, SHORT
    quantity: float = 0.0
    entry_price: float = Field(default=0.0, ge=0.0)
    current_price: float = Field(default=0.0, ge=0.0)
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    leverage: int = Field(default=10, gt=0)
    margin: float = Field(default=0.0, ge=0.0)
    liquidation_price: float = Field(default=0.0, ge=0.0)

    @field_validator('*', mode='before')
    @classmethod
    def check_floats(cls, v, info):
        return check_not_nan_inf(v, info.field_name)

class PortfolioState(BaseModel):
    """Canonical representation of the overall account."""
    wallet_balance: float
    equity: float
    used_margin: float = Field(ge=0.0)
    free_margin: float
    total_unrealized_pnl: float
    total_exposure: float = Field(ge=0.0)
    positions: Dict[str, PositionState] = Field(default_factory=dict)

    @field_validator('*', mode='before')
    @classmethod
    def check_floats(cls, v, info):
        return check_not_nan_inf(v, info.field_name)

class MacroState(BaseModel):
    """Canonical representation of external market conditions."""
    timestamp: float = Field(gt=0)
    sentiment_score: float = Field(default=0.0, ge=-1.0, le=1.0)
    volatility_expectation: float = Field(default=0.5, ge=0.0)
    regime: float = 0.0
    headlines: list[str] = Field(default_factory=list)

    @field_validator('*', mode='before')
    @classmethod
    def check_floats(cls, v, info):
        if info.field_name == "headlines":
            return v
        return check_not_nan_inf(v, info.field_name)

class NewsState(BaseModel):
    timestamp: float
    source: str
    headline: str
    sentiment: float = Field(ge=-1.0, le=1.0)

class EventState(BaseModel):
    timestamp: float
    event_type: str
    impact_score: float = Field(ge=-1.0, le=1.0)

class Action(BaseModel):
    symbol: str
    action_type: str
    confidence: float = Field(ge=0.0, le=1.0)
    target_size: float = Field(ge=0.0, le=1.0)

class OrderRequest(BaseModel):
    """Canonical request generated by the AI / Execution engine."""
    symbol: str
    action_type: str # OPEN_LONG, OPEN_SHORT, CLOSE_LONG, CLOSE_SHORT, HOLD
    confidence: float = Field(ge=0.0, le=1.0)
    requested_quantity: float = Field(ge=0.0)
    target_position: float = Field(ge=0.0, le=1.0)
    model_version: str
    timestamp: float = Field(gt=0)

class OrderResult(BaseModel):
    order_id: str
    symbol: str
    status: str
    filled_quantity: float = Field(ge=0.0)
    average_price: float = Field(ge=0.0)
    error_message: Optional[str] = None

class RiskDecision(BaseModel):
    """Deterministic result from the RiskManager."""
    approved: bool
    reason: str
    adjusted_quantity: float = Field(ge=0.0)
    max_allowed_quantity: float = Field(ge=0.0)
    risk_flags: List[str] = Field(default_factory=list)

class Experience(BaseModel):
    timestamp: float
    symbol: str
    market_state_json: str
    portfolio_state_json: str
    action_type: str
    reward: float
    done: bool
