"""Update Experience table for Futures

Revision ID: 29a7daed53a7
Revises: 
Create Date: 2026-09-11 16:36:25.908083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a7daed53a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('market_state', sa.JSON(), nullable=True),
    sa.Column('derivatives_state', sa.JSON(), nullable=True),
    sa.Column('news_state', sa.JSON(), nullable=True),
    sa.Column('macro_state', sa.JSON(), nullable=True),
    sa.Column('crypto_state', sa.JSON(), nullable=True),
    sa.Column('sentiment_state', sa.JSON(), nullable=True),
    sa.Column('account_state', sa.JSON(), nullable=True),
    sa.Column('portfolio_state', sa.JSON(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('action_probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('position_before', sa.Float(), nullable=True),
    sa.Column('position_after', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('funding_cost', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('holding_duration', sa.Integer(), nullable=True),
    sa.Column('market_regime', sa.String(length=50), nullable=True),
    sa.Column('event_context', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('next_state', sa.JSON(), nullable=True),
    sa.Column('episode_id', sa.String(length=64), nullable=True),
    sa.Column('data_quality_flags', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_episode_id'), 'experiences', ['episode_id'], unique=False)
    op.create_index(op.f('ix_experiences_experience_id'), 'experiences', ['experience_id'], unique=True)
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_index(op.f('ix_experiences_model_version'), 'experiences', ['model_version'], unique=False)
    op.create_index(op.f('ix_experiences_symbol'), 'experiences', ['symbol'], unique=False)
    op.create_index(op.f('ix_experiences_timestamp'), 'experiences', ['timestamp'], unique=False)
    op.create_table('market_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_features_id'), 'market_features', ['id'], unique=False)
    op.create_index(op.f('ix_market_features_symbol'), 'market_features', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_features_timestamp'), 'market_features', ['timestamp'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.String(length=50), nullable=False),
    sa.Column('architecture', sa.String(length=100), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('checkpoint_path', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_model_versions_version_id'), 'model_versions', ['version_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('executed_quantity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_exchange_order_id'), 'orders', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=10), nullable=False),
    sa.Column('quote_asset', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('TRADING', 'HALTED', 'BREAK', name='symbolstatus'), nullable=True),
    sa.Column('trading_enabled', sa.Boolean(), nullable=True),
    sa.Column('min_quantity', sa.Float(), nullable=True),
    sa.Column('max_quantity', sa.Float(), nullable=True),
    sa.Column('quantity_step', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('price_tick', sa.Float(), nullable=True),
    sa.Column('min_notional', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_model_versions_version_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_market_features_timestamp'), table_name='market_features')
    op.drop_index(op.f('ix_market_features_symbol'), table_name='market_features')
    op.drop_index(op.f('ix_market_features_id'), table_name='market_features')
    op.drop_table('market_features')
    op.drop_index(op.f('ix_experiences_timestamp'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_symbol'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_model_version'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_experience_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_episode_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
