"""Add missing Experience columns

Revision ID: 482e83b7bfa3
Revises: 29a7daed53a7
Create Date: 2026-09-17 15:57:53.582036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '482e83b7bfa3'
down_revision: Union[str, None] = '29a7daed53a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('experiences', sa.Column('derivatives_state', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('news_state', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('crypto_state', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('sentiment_state', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('account_state', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('action', sa.String(length=20), nullable=True))
    op.add_column('experiences', sa.Column('action_probability', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('position_before', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('position_after', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('leverage', sa.Integer(), nullable=True))
    op.add_column('experiences', sa.Column('margin', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('funding_cost', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('slippage', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('unrealized_pnl', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('holding_duration', sa.Integer(), nullable=True))
    op.add_column('experiences', sa.Column('market_regime', sa.String(length=50), nullable=True))
    op.add_column('experiences', sa.Column('latency', sa.Float(), nullable=True))
    op.add_column('experiences', sa.Column('episode_id', sa.String(length=64), nullable=True))
    op.add_column('experiences', sa.Column('data_quality_flags', sa.String(length=200), nullable=True))
    op.alter_column('experiences', 'experience_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               nullable=True)
    op.alter_column('experiences', 'timestamp',
               existing_type=mysql.FLOAT(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('experiences', 'symbol',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('experiences', 'event_context',
               existing_type=mysql.JSON(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('experiences', 'model_version',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_experiences_experience_id'), table_name='experiences')
    op.create_index(op.f('ix_experiences_experience_id'), 'experiences', ['experience_id'], unique=True)
    op.create_index(op.f('ix_experiences_episode_id'), 'experiences', ['episode_id'], unique=False)
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_index(op.f('ix_experiences_model_version'), 'experiences', ['model_version'], unique=False)
    op.drop_column('experiences', 'drawdown')
    op.drop_column('experiences', 'data_quality')
    op.drop_column('experiences', 'approved_size')
    op.drop_column('experiences', 'position_state')
    op.drop_column('experiences', 'requested_size')
    op.drop_column('experiences', 'action_type')
    op.drop_column('experiences', 'regime')
    op.drop_column('experiences', 'done')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('experiences', sa.Column('regime', mysql.FLOAT(), nullable=True))
    op.add_column('experiences', sa.Column('action_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('experiences', sa.Column('requested_size', mysql.FLOAT(), nullable=True))
    op.add_column('experiences', sa.Column('position_state', mysql.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('approved_size', mysql.FLOAT(), nullable=True))
    op.add_column('experiences', sa.Column('data_quality', mysql.FLOAT(), nullable=True))
    op.add_column('experiences', sa.Column('drawdown', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_experiences_model_version'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_episode_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_experience_id'), table_name='experiences')
    op.create_index(op.f('ix_experiences_experience_id'), 'experiences', ['experience_id'], unique=False)
    op.alter_column('experiences', 'model_version',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('experiences', 'event_context',
               existing_type=sa.String(length=100),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('experiences', 'symbol',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('experiences', 'timestamp',
               existing_type=sa.BigInteger(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('experiences', 'experience_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               nullable=False)
    op.drop_column('experiences', 'data_quality_flags')
    op.drop_column('experiences', 'episode_id')
    op.drop_column('experiences', 'latency')
    op.drop_column('experiences', 'market_regime')
    op.drop_column('experiences', 'holding_duration')
    op.drop_column('experiences', 'unrealized_pnl')
    op.drop_column('experiences', 'slippage')
    op.drop_column('experiences', 'funding_cost')
    op.drop_column('experiences', 'margin')
    op.drop_column('experiences', 'leverage')
    op.drop_column('experiences', 'position_after')
    op.drop_column('experiences', 'position_before')
    op.drop_column('experiences', 'action_probability')
    op.drop_column('experiences', 'action')
    op.drop_column('experiences', 'account_state')
    op.drop_column('experiences', 'sentiment_state')
    op.drop_column('experiences', 'crypto_state')
    op.drop_column('experiences', 'news_state')
    op.drop_column('experiences', 'derivatives_state')
    op.drop_column('experiences', 'id')
    # ### end Alembic commands ###
